### ISSUE TITLE
Hyper-parameters asking! 

### ISSUE THREAD

**Issue by KeranLi** [inwins27/Fractal-Dimension#1]
Hi, @ajaychawda58 !

Recently I'm trying to analyze the fractal-dimension in colorful images. Your work is really helpful in calculating the box-count fractal-dimensions. However, I'm not clear about your ipynb file, in:
<q = 0.21*float(red_max) + 0.72*float(green_max) + 0.07*float(blue_max)>
So why the three parameters are set as 0.21, 0.72 and 0.07?

**Comment by ajaychawda58** [comment]
@KeranLi Glad that you're able to use our work. That would be to set the max limits due to color conversion from RGB to HSV. The Python notebook is just for one scenario. For a better understanding, please refer to Matlab scripts, which are implemented by @natsu1628 for the paper.
